config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    member do
      get :sign_in
    end
  end

  get '/sign_in', controller: 'messages', action: 'sign_in'

  root "messages#sign_in"
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new(user: user_from_param)
    @messages = Message.last(50)
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      @message.save
      render json: {status: 'success', message: @message}
    else
      render json: {status: 'error', error: @message.errors}
    end
  end

  def sign_in
  end


    private

    def message_params
      params.permit![:message]
    end

    def user_from_param
      params.permit![:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuildChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <%= f.hidden_field :user %>
  <%= f.text_field :body %>
  <%= f.submit 'Send', data: {disable_with: false} %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <span class="message_user">
    <b><%= message.user %>: </b>
  </span>
  <span class="message_body">
    <%= message.body %>
  </span>
</div>

app/views/messages/index.html.erb
<h1> Guild Chat App</h1>
<div id="messages" >
<% @messages.each do |message| %>
  <div class="message">
    <span class="message_user">
      <b><%= message.user %>: </b>
    </span>
    <span class="message_body">
      <%= message.body %>
    </span>
  </div>
<% end %>
</div>

<%= render 'form' %>

app/views/messages/sign_in.html.erb
<h1>Guild Chat App</h1>
<h2>Please select a user below:</h2>
<div>
  <%= link_to 'Alice', messages_path(Message.new, user: 'alice') %>
</div>
<div>
  <%= link_to 'Bob', messages_path(Message.new, user: 'bob') %>
</div>